version: "3"
services:

  webserver:
    image: nginx:alpine
    container_name: realestate-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./phpdocker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
    ports:
      - "83:80"
      - "81:81"
      - "443:443"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: realestate-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - APP_ENV=dev
      - API_URL=http://realestate.wiseweb.pl/api/

  composer:
    restart: 'no'
    container_name: realestate-composer
    image: prooph/composer:7.2
    command: install
    volumes:
      - .:/application
