version: "3"
services:
  mysql:
    image: mariadb:10.2
    container_name: realestate-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3308:3306"

  webserver:
    image: nginx:alpine
    container_name: realestate-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./phpdocker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
    ports:
      - "84:80"
      - "82:81"
      - "444:443"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: realestate-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - APP_ENV=prod
      - API_URL=http://realestate.wiseweb.pl/api/

  composer:
    restart: 'no'
    container_name: realestate-composer
    image: prooph/composer:7.2
    command: install
    volumes:
      - .:/application
