version: "3"
services:
  redis:
    image: redis:alpine
    container_name: realestate-redis

  mysql:
    image: mariadb:10.2
    container_name: realestate-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 9191:80
    environment:
      MYSQL_USERNAME: test
      MYSQL_ROOT_PASSWORD: test
      PMA_HOST: realestate-mysql

  webserver:
    image: nginx:alpine
    container_name: realestate-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./phpdocker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
    ports:
      - "84:80"
      - "82:81"
      - "444:443"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: realestate-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - APP_ENV=dev
      - API_URL=http://cms.porownaj-czynsz.pl/api/
      - DATABASE_URL=mysql://test:test@realestate-mysql:3306/test
      - MAILER_GMAIL_USERNAME=matixe
      - MAILER_GMAIL_PASSWORD=C7BY8H3WYsg2hept72
      - REDIS_URL=redis://realestate-redis

  composer:
    restart: 'no'
    container_name: realestate-composer
    image: prooph/composer:7.2
    command: install
    volumes:
      - .:/application
