version: '3'
services:
    apache:
        build: .docker/apache
        container_name: porownaj_apache
        ports:
          - 60:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/dawid/Documents/Projects/porownywarka/porownajczynsz
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: porownaj_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    php:
        build: .docker/php
        container_name: porownaj_php
        volumes:
          - .:/home/dawid/Documents/Projects/porownywarka/porownajczynsz
        environment:
          - maildev_host=porownaj_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: porownaj_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: porownaj_maildev
        ports:
          - 8001:80
