<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.handler_stack.api_client' shared service.

$this->services['eight_points_guzzle.handler_stack.api_client'] = $instance = \GuzzleHttp\HandlerStack::create();

$instance->push(($this->services['eight_points_guzzle.middleware.log.api_client'] ?? $this->load('getEightPointsGuzzle_Middleware_Log_ApiClientService.php'))->log(), 'log');
$instance->after('log', ($this->services['eight_points_guzzle.middleware.request_time.api_client'] ?? $this->load('getEightPointsGuzzle_Middleware_RequestTime_ApiClientService.php')), 'request_time');
$instance->push(($this->services['eight_points_guzzle.middleware.symfony_log'] ?? $this->load('getEightPointsGuzzle_Middleware_SymfonyLogService.php')), 'symfony_log');
$instance->push(($this->services['eight_points_guzzle.middleware.profile.api_client'] ?? $this->load('getEightPointsGuzzle_Middleware_Profile_ApiClientService.php'))->profile(), 'profile');
$instance->unshift(($this->services['eight_points_guzzle.middleware.event_dispatch.api_client'] ?? $this->load('getEightPointsGuzzle_Middleware_EventDispatch_ApiClientService.php'))->dispatchEvent(), 'events');

return $instance;
