<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.middleware.event_dispatch.api_client' shared service.

return $this->services['eight_points_guzzle.middleware.event_dispatch.api_client'] = new \EightPoints\Bundle\GuzzleBundle\Middleware\EventDispatchMiddleware(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), 'api_client');
