<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.symfony_log_formatter' shared service.

return $this->services['eight_points_guzzle.symfony_log_formatter'] = new \GuzzleHttp\MessageFormatter('{method} {uri} {code}');
