<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhW7xaM\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhW7xaM/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKhW7xaM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKhW7xaM\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerKhW7xaM\srcApp_KernelProdContainer([
    'container.build_hash' => 'KhW7xaM',
    'container.build_id' => 'fe4a2be1',
    'container.build_time' => 1551806725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKhW7xaM');
