<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerARR0z1t\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerARR0z1t/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerARR0z1t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerARR0z1t\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerARR0z1t\srcApp_KernelProdContainer([
    'container.build_hash' => 'ARR0z1t',
    'container.build_id' => '1e76903c',
    'container.build_time' => 1551813814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerARR0z1t');
