<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.middleware.request_time.my_client' shared service.

return $this->services['eight_points_guzzle.middleware.request_time.my_client'] = new \EightPoints\Bundle\GuzzleBundle\Middleware\RequestTimeMiddleware(($this->services['eight_points_guzzle.logger'] ?? ($this->services['eight_points_guzzle.logger'] = new \EightPoints\Bundle\GuzzleBundle\Log\Logger())), ($this->privates['eight_points_guzzle.data_collector'] ?? $this->getEightPointsGuzzle_DataCollectorService()));
