<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PageController::recentChart' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController::recentCities' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController::show' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController:recentChart' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController:recentCities' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController:show' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
