<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v1OQ66R' shared service.

return $this->privates['.service_locator.v1OQ66R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cityService' => ['privates', 'App\\Service\\CityService', 'getCityServiceService.php', true],
]);
