<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8NzzRpx' shared service.

return $this->privates['.service_locator.8NzzRpx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cityService' => ['privates', 'App\\Service\\CityService', 'getCityServiceService.php', true],
    'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', false],
]);
