<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\LandingController::getBills' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\LandingController::getCityValues' => ['privates', '.service_locator.kJaRQ3X', 'get_ServiceLocator_KJaRQ3XService.php', true],
    'App\\Controller\\LandingController::index' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\LandingController::postBills' => ['privates', '.service_locator.8NzzRpx', 'get_ServiceLocator_8NzzRpxService.php', true],
    'App\\Controller\\LandingController::postCityValues' => ['privates', '.service_locator.8NzzRpx', 'get_ServiceLocator_8NzzRpxService.php', true],
    'App\\Controller\\PageController::recentChart' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\PageController::recentCities' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController::show' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\LandingController:getBills' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\LandingController:getCityValues' => ['privates', '.service_locator.kJaRQ3X', 'get_ServiceLocator_KJaRQ3XService.php', true],
    'App\\Controller\\LandingController:index' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\LandingController:postBills' => ['privates', '.service_locator.8NzzRpx', 'get_ServiceLocator_8NzzRpxService.php', true],
    'App\\Controller\\LandingController:postCityValues' => ['privates', '.service_locator.8NzzRpx', 'get_ServiceLocator_8NzzRpxService.php', true],
    'App\\Controller\\PageController:recentChart' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
    'App\\Controller\\PageController:recentCities' => ['privates', '.service_locator.Dt0mQ8P', 'get_ServiceLocator_Dt0mQ8PService.php', true],
    'App\\Controller\\PageController:show' => ['privates', '.service_locator.l5Fkjoo', 'get_ServiceLocator_L5FkjooService.php', true],
]));
