<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\CityService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/CityService.php';

return $this->privates['App\Service\CityService'] = new \App\Service\CityService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['jms_serializer'] ?? $this->getJmsSerializerService()), ($this->services['App\Service\ApiClientService'] ?? $this->getApiClientServiceService()));
