<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM12YVJi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM12YVJi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM12YVJi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM12YVJi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM12YVJi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M12YVJi',
    'container.build_id' => 'f570b5e3',
    'container.build_time' => 1550835190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM12YVJi');
