<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHduOS17\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHduOS17/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHduOS17.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHduOS17\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHduOS17\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HduOS17',
    'container.build_id' => 'e73c87b7',
    'container.build_time' => 1551806253,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHduOS17');
