<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRSnQYEk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRSnQYEk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRSnQYEk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRSnQYEk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRSnQYEk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RSnQYEk',
    'container.build_id' => 'f2e693ea',
    'container.build_time' => 1550776487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRSnQYEk');
