<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Dt0mQ8P' shared service.

return $this->privates['.service_locator.Dt0mQ8P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'apiClientService' => ['services', 'App\\Service\\ApiClientService', 'getApiClientServiceService', false],
]);
